### ISSUE TITLE
Update translations with new/changed strings

### ISSUE THREAD

**Issue by Wartybix** [Wartybix/GNOME-Auto-Accent-Colour#4]
- [x] US translation
- [x] Italian translation
- [x] German translation

**Comment by Wartybix** [comment]
@amivaleo @daPhipz just letting you know some strings have been added/changed since your last translations. If you're interested in updating the PO files, I've regenerated them with the handy script @daPhipz gave, so they already have the new `msgid`s and `fuzzy` tags applied to changed strings, they just need the `msgstr`s updating. Thanks again for your existing contributions to this project.

**Comment by amivaleo** [comment]
Hi!
Yes, yes! I'm already working on it! :)
